// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqZ_xqK9XC-LfaKYG0X59ld6aGOdBEjeI',
    appId: '1:772290278222:web:e15b13a25ef6c4e241641f',
    messagingSenderId: '772290278222',
    projectId: 'tapguard-0',
    authDomain: 'tapguard-0.firebaseapp.com',
    storageBucket: 'tapguard-0.firebasestorage.app',
    measurementId: 'G-4756TBC9BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW2eZVyyT3nB63PCJv2gbHdNPUSQbQj0M',
    appId: '1:772290278222:android:c69af8c3d673247541641f',
    messagingSenderId: '772290278222',
    projectId: 'tapguard-0',
    storageBucket: 'tapguard-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4lfOYKtPgoA_JiGBK8Y-GgMsm9B4U8hU',
    appId: '1:772290278222:ios:930fcb5409fa462941641f',
    messagingSenderId: '772290278222',
    projectId: 'tapguard-0',
    storageBucket: 'tapguard-0.firebasestorage.app',
    iosBundleId: 'com.example.tapguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4lfOYKtPgoA_JiGBK8Y-GgMsm9B4U8hU',
    appId: '1:772290278222:ios:930fcb5409fa462941641f',
    messagingSenderId: '772290278222',
    projectId: 'tapguard-0',
    storageBucket: 'tapguard-0.firebasestorage.app',
    iosBundleId: 'com.example.tapguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqZ_xqK9XC-LfaKYG0X59ld6aGOdBEjeI',
    appId: '1:772290278222:web:b6248337aae4952d41641f',
    messagingSenderId: '772290278222',
    projectId: 'tapguard-0',
    authDomain: 'tapguard-0.firebaseapp.com',
    storageBucket: 'tapguard-0.firebasestorage.app',
    measurementId: 'G-SFVCTD1ND1',
  );

}